/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import ModeloConection.ConexaoBD;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import ModeloDao.DaoUsuario;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.BeansUsuario;
import modeloBeans.ModeloTabela;

/**
 *
 * @author Daiana Barbosa
 */
public class FormUsuario extends javax.swing.JFrame {

    BeansUsuario mod = new BeansUsuario();
    DaoUsuario dao = new DaoUsuario();
    ConexaoBD conex = new ConexaoBD();
    int flag = 0;

    /**
     * Creates new form Usuario
     */
    public FormUsuario() {
        initComponents();
    }

    public void preencherTabela(String sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Cod", "Nome", "Senha", "Tipo"};
        conex.conexao();
        conex.executasql(sql);
        try {
            conex.rs.first();
            do {
                dados.add(new Object[]{conex.rs.getInt("cod_usu"), conex.rs.getString("nome_usu"), conex.rs.getString("senha_usu"), conex.rs.getString("tipo_usu")});
            } while (conex.rs.next());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "busca n encontrada");
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTablebusca.setModel(modelo);
        jTablebusca.getColumnModel().getColumn(0).setPreferredWidth(33);
        jTablebusca.getColumnModel().getColumn(0).setResizable(false);
        jTablebusca.getColumnModel().getColumn(1).setPreferredWidth(225);
        jTablebusca.getColumnModel().getColumn(1).setResizable(false);
        jTablebusca.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTablebusca.getColumnModel().getColumn(2).setResizable(false);
        jTablebusca.getColumnModel().getColumn(3).setPreferredWidth(90);
        jTablebusca.getColumnModel().getColumn(3).setResizable(false);
        jTablebusca.getTableHeader().setReorderingAllowed(false);
        jTablebusca.setAutoResizeMode(jTablebusca.AUTO_RESIZE_OFF);
        jTablebusca.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        conex.desconect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldusuario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPasswordFieldsenha = new javax.swing.JPasswordField();
        jPasswordFieldsenha2 = new javax.swing.JPasswordField();
        jComboBoxtipo = new javax.swing.JComboBox();
        jButtonnovo = new javax.swing.JButton();
        jButtoneditar = new javax.swing.JButton();
        jButtonsalvar = new javax.swing.JButton();
        jButtonexcluir = new javax.swing.JButton();
        jButtoncancelar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jTextFieldbusca = new javax.swing.JTextField();
        jButtonpesquiza = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablebusca = new javax.swing.JTable();
        jTextFieldid = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setEnabled(false);
        jFrame1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                jFrame1WindowActivated(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel8.setText("Cadastro de Usuários");

        jPanel3.setBackground(new java.awt.Color(223, 210, 236));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, new java.awt.Color(204, 0, 204)));
        jPanel3.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel10.setText("Usuário:");

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel11.setText("Senha:");

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel12.setText("Confirmar Senha:");

        jTextFieldusuario.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel13.setText("Tipo:");

        jPasswordFieldsenha.setEnabled(false);

        jPasswordFieldsenha2.setEnabled(false);
        jPasswordFieldsenha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldsenha2ActionPerformed(evt);
            }
        });

        jComboBoxtipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Médico", "Recepcionista" }));
        jComboBoxtipo.setEnabled(false);
        jComboBoxtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxtipoActionPerformed(evt);
            }
        });

        jButtonnovo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButtonnovo.setText("Novo");
        jButtonnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnovoActionPerformed(evt);
            }
        });

        jButtoneditar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButtoneditar.setText("Editar");
        jButtoneditar.setEnabled(false);
        jButtoneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoneditarActionPerformed(evt);
            }
        });

        jButtonsalvar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButtonsalvar.setText("Salvar");
        jButtonsalvar.setEnabled(false);
        jButtonsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsalvarActionPerformed(evt);
            }
        });

        jButtonexcluir.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButtonexcluir.setText("Excluir");
        jButtonexcluir.setEnabled(false);
        jButtonexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonexcluirActionPerformed(evt);
            }
        });

        jButtoncancelar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButtoncancelar.setText("Cancelar");
        jButtoncancelar.setEnabled(false);
        jButtoncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncancelarActionPerformed(evt);
            }
        });

        jButtonpesquiza.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButtonpesquiza.setText("Pesquisar");
        jButtonpesquiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpesquizaActionPerformed(evt);
            }
        });

        jTablebusca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "SENHA", "TIPO"
            }
        ));
        jTablebusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablebuscaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTablebusca);

        jTextFieldid.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel14.setText("ID:");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daiana Barbosa\\Desktop\\Sem Título-1.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jPasswordFieldsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel12)))
                                .addGap(12, 12, 12)
                                .addComponent(jPasswordFieldsenha2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jSeparator2))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jTextFieldbusca, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonpesquiza))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jButtonnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtoncancelar))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldid, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtoneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jPasswordFieldsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordFieldsenha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jComboBoxtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonnovo)
                    .addComponent(jButtoneditar)
                    .addComponent(jButtonsalvar)
                    .addComponent(jButtonexcluir)
                    .addComponent(jButtoncancelar))
                .addGap(20, 20, 20)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldbusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonpesquiza))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(26, 26, 26)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxtipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxtipoActionPerformed

    private void jButtonnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnovoActionPerformed
        flag = 1;
        jButtonnovo.setEnabled(false);
        jTextFieldusuario.setEnabled(true);
        jComboBoxtipo.setEnabled(true);
        jPasswordFieldsenha.setEnabled(true);
        jPasswordFieldsenha2.setEnabled(true);
        jTextFieldbusca.setEnabled(false);
        jButtonpesquiza.setEnabled(false);
        jButtoneditar.setEnabled(false);
        jButtonexcluir.setEnabled(false);
        jButtonsalvar.setEnabled(true);
        jTextFieldusuario.setEnabled(true);
        jPasswordFieldsenha.setEnabled(true);
        jPasswordFieldsenha2.setEnabled(true);
        jButtoncancelar.setEnabled(false);
        jComboBoxtipo.setEnabled(true);
    }//GEN-LAST:event_jButtonnovoActionPerformed

    private void jButtoneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoneditarActionPerformed
        flag = 2;
        jButtonsalvar.setEnabled(true);
        jTextFieldusuario.setEnabled(true);
        jPasswordFieldsenha.setEnabled(true);
        jPasswordFieldsenha2.setEnabled(true);
        jButtoncancelar.setEnabled(true);
        jComboBoxtipo.setEnabled(true);
        jButtoneditar.setEnabled(false);
        jButtonnovo.setEnabled(false);
        jButtonexcluir.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtoneditarActionPerformed

    private void jButtonsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsalvarActionPerformed
        if (jTextFieldusuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo usuario precisa ser preenchido");
            jTextFieldusuario.requestFocus();
        } else if (jPasswordFieldsenha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo senha precisa ser preenchido antes de salvar");
            jPasswordFieldsenha.requestFocus();
        } else if (!(jPasswordFieldsenha.getText()).equals(jPasswordFieldsenha2.getText())) {
            JOptionPane.showMessageDialog(null, "A senha e a confirmação da senha devem ser as mesmas");
        } else if (jPasswordFieldsenha2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo confirmação de senha deve ser preenchido");
        } else if (flag == 1) {
            mod.setNome(jTextFieldusuario.getText());
            mod.setSenha((jPasswordFieldsenha.getText()));
            mod.setTipo((String) jComboBoxtipo.getSelectedItem());
            dao.salvar(mod);
            jTextFieldusuario.setText("");
            jPasswordFieldsenha.setText("");
            jPasswordFieldsenha2.setText("");
            jTextFieldusuario.setEnabled(false);
            jPasswordFieldsenha.setEnabled(false);
            jPasswordFieldsenha2.setEnabled(false);
            jComboBoxtipo.setEnabled(false);
            jButtonsalvar.setEnabled(false);
            jTextFieldid.setText("");
            jTextFieldbusca.setText("");
            jButtoncancelar.setEnabled(false);
            jTextFieldbusca.setEnabled(true);
            jButtonpesquiza.setEnabled(true);
            jButtonnovo.setEnabled(true);
            jButtoneditar.setEnabled(false);

        } else {
            mod.setCod(Integer.parseInt(jTextFieldid.getText()));
            mod.setNome(jTextFieldusuario.getText());
            mod.setTipo((String) (jComboBoxtipo.getSelectedItem()));
            mod.setSenha((String) (jPasswordFieldsenha.getText()));
            dao.editar(mod);
            jTextFieldusuario.setEnabled(false);
            jPasswordFieldsenha.setEnabled(false);
            jPasswordFieldsenha2.setEnabled(false);
            jComboBoxtipo.setEnabled(false);
            jButtonsalvar.setEnabled(false);
            jTextFieldusuario.setText("");
            jPasswordFieldsenha2.setText("");
            jPasswordFieldsenha.setText("");
            jButtonnovo.setEnabled(true);
            jButtoncancelar.setEnabled(false);
            jTextFieldid.setText("");
            jTextFieldbusca.setText("");
            jButtoneditar.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonsalvarActionPerformed

    private void jButtonexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonexcluirActionPerformed
        int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir o cadastro?");
        if (resposta == JOptionPane.YES_OPTION) {
            mod.setCod(Integer.parseInt(jTextFieldid.getText()));
            dao.excluir(mod);
            jTextFieldid.setText("");
            jTextFieldusuario.setText("");
            jPasswordFieldsenha.setText("");
            jPasswordFieldsenha2.setText("");

            jTextFieldid.setEnabled(false);
            jTextFieldusuario.setEnabled(false);
            jPasswordFieldsenha2.setEnabled(false);
            jPasswordFieldsenha.setEnabled(false);
            jButtonnovo.setEnabled(true);
            jButtoncancelar.setEnabled(false);
            jButtoneditar.setEnabled(false);
            jButtonexcluir.setEnabled(false);
            jButtonsalvar.setEnabled(false);
            jButtonexcluir.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonexcluirActionPerformed

    private void jButtoncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncancelarActionPerformed
        jButtonsalvar.setEnabled(false);
        jTextFieldusuario.setEnabled(false);
        jPasswordFieldsenha.setEnabled(false);
        jPasswordFieldsenha2.setEnabled(false);
        jButtoncancelar.setEnabled(false);
        jButtonpesquiza.setEnabled(true);
        jTextFieldbusca.setEnabled(true);
        jComboBoxtipo.setEnabled(false);
        jButtonnovo.setEnabled(true);
        jButtoneditar.setEnabled(false);
        jButtonexcluir.setEnabled(false);
        jTextFieldusuario.setText("");
        jTextFieldbusca.setText("");
        jTextFieldid.setText("");
        jPasswordFieldsenha.setText("");
        jPasswordFieldsenha2.setText("");

    }//GEN-LAST:event_jButtoncancelarActionPerformed

    private void jPasswordFieldsenha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldsenha2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldsenha2ActionPerformed

    private void jButtonpesquizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpesquizaActionPerformed
        jTextFieldusuario.setText("");
        jPasswordFieldsenha.setText("");
        jPasswordFieldsenha2.setText("");
        jTextFieldid.setText("");
        mod.setPesquiza(jTextFieldbusca.getText());
        BeansUsuario model = dao.buscaUsuario(mod);
        jTextFieldid.setText(String.valueOf(model.getCod()));
        jTextFieldusuario.setText(model.getNome());
        jPasswordFieldsenha.setText(String.valueOf(model.getSenha()));
        jComboBoxtipo.setSelectedItem(model.getTipo());
        jButtoneditar.setEnabled(!true);
        jButtonexcluir.setEnabled(!true);
        preencherTabela("select * from usuarios where nome_usu like '%" + mod.getPesquiza() + "%'");
    }//GEN-LAST:event_jButtonpesquizaActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        preencherTabela("select *from usuarios order by nome_usu");
    }//GEN-LAST:event_formWindowActivated

    private void jTablebuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablebuscaMouseClicked
        String nome_usu = "" + jTablebusca.getValueAt(jTablebusca.getSelectedRow(), 1);
        conex.conexao();
        conex.executasql("select * from usuarios where nome_usu='" + nome_usu + "'");
        try {
            conex.rs.first();
            jTextFieldid.setText(String.valueOf(conex.rs.getInt("cod_usu")));
            jTextFieldusuario.setText(conex.rs.getString("nome_usu"));
            jPasswordFieldsenha.setText(String.valueOf(conex.rs.getInt("senha_usu")));
            jPasswordFieldsenha2.setText(String.valueOf(conex.rs.getInt("senha_usu")));
            jComboBoxtipo.setSelectedItem(conex.rs.getString("tipo_usu"));
        } catch (SQLException ex) {
            Logger.getLogger(FormMedico.class.getName()).log(Level.SEVERE, null, ex);
        }
        jButtoneditar.setEnabled(true);
        jButtonexcluir.setEnabled(true);
        jButtoncancelar.setEnabled(true);
        jButtonnovo.setEnabled(false);
        conex.desconect();
    }//GEN-LAST:event_jTablebuscaMouseClicked

    private void jFrame1WindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame1WindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_jFrame1WindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtoncancelar;
    private javax.swing.JButton jButtoneditar;
    private javax.swing.JButton jButtonexcluir;
    private javax.swing.JButton jButtonnovo;
    private javax.swing.JButton jButtonpesquiza;
    private javax.swing.JButton jButtonsalvar;
    private javax.swing.JComboBox jComboBoxtipo;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordFieldsenha;
    private javax.swing.JPasswordField jPasswordFieldsenha2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTablebusca;
    private javax.swing.JTextField jTextFieldbusca;
    private javax.swing.JTextField jTextFieldid;
    private javax.swing.JTextField jTextFieldusuario;
    // End of variables declaration//GEN-END:variables
}
