/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;
import javax.swing.table.DefaultTableModel;
import ModeloConection.ConexaoBD;
import static java.lang.Integer.parseInt;
import ModeloDao.DaoMedico;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import modeloBeans.BeansMedico;
import modeloBeans.ModeloTabela;
import static sun.util.calendar.CalendarUtils.mod;
import static sun.util.calendar.CalendarUtils.mod;
import static sun.util.calendar.CalendarUtils.mod;

/**
 *
 * @author Daiana Barbosa
 */
public class FormMedico extends javax.swing.JFrame {
BeansMedico mod =new BeansMedico();
DaoMedico dao =new DaoMedico();
ConexaoBD conex=new ConexaoBD();

int flag=0;
    public FormMedico() {
        initComponents();
      //  preencherTabela("select *from medicos order by nome_medico");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelfundo = new javax.swing.JPanel();
        jLabelnome = new javax.swing.JLabel();
        jLabelcrm = new javax.swing.JLabel();
        jLabelespecialização = new javax.swing.JLabel();
        jTextFieldnome = new javax.swing.JTextField();
        jTextFieldcrm = new javax.swing.JTextField();
        jComboBoxespecializações = new javax.swing.JComboBox();
        jButtonnovo = new javax.swing.JButton();
        jButtoneditar = new javax.swing.JButton();
        jButtonsalvar = new javax.swing.JButton();
        jButtonexcluir = new javax.swing.JButton();
        jButtoncancelar = new javax.swing.JButton();
        jTextFieldbusca = new javax.swing.JTextField();
        jLabelbusca = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablebusca = new javax.swing.JTable();
        jButtonpesquiza = new javax.swing.JButton();
        jLabelid = new javax.swing.JLabel();
        jTextFieldid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelcadastro = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelfundo.setBackground(new java.awt.Color(223, 210, 236));
        jPanelfundo.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, new java.awt.Color(204, 0, 204)));

        jLabelnome.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelnome.setText("Nome:");

        jLabelcrm.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelcrm.setText("CRM:");

        jLabelespecialização.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelespecialização.setText("Especialização:");
        jLabelespecialização.setEnabled(false);

        jTextFieldnome.setEnabled(false);

        jTextFieldcrm.setEnabled(false);

        jComboBoxespecializações.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jComboBoxespecializações.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cirusgião", "Dentista", "Cardiologista", "Oftamologista", "Ortopedista", " " }));
        jComboBoxespecializações.setEnabled(false);
        jComboBoxespecializações.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxespecializaçõesActionPerformed(evt);
            }
        });

        jButtonnovo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButtonnovo.setText("Novo");
        jButtonnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnovoActionPerformed(evt);
            }
        });

        jButtoneditar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButtoneditar.setText("Editar");
        jButtoneditar.setEnabled(false);
        jButtoneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoneditarActionPerformed(evt);
            }
        });

        jButtonsalvar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButtonsalvar.setText("Salvar");
        jButtonsalvar.setEnabled(false);
        jButtonsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsalvarActionPerformed(evt);
            }
        });

        jButtonexcluir.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButtonexcluir.setText("Excluir");
        jButtonexcluir.setEnabled(false);
        jButtonexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonexcluirActionPerformed(evt);
            }
        });

        jButtoncancelar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButtoncancelar.setText("Cancelar");
        jButtoncancelar.setEnabled(false);
        jButtoncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncancelarActionPerformed(evt);
            }
        });

        jTextFieldbusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldbuscaActionPerformed(evt);
            }
        });

        jLabelbusca.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelbusca.setText("Busca:");

        jTablebusca.setBackground(new java.awt.Color(204, 102, 255));
        jTablebusca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablebusca.setSelectionBackground(new java.awt.Color(204, 0, 204));
        jTablebusca.setSelectionForeground(new java.awt.Color(0, 0, 153));
        jTablebusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablebuscaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTablebusca);

        jButtonpesquiza.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButtonpesquiza.setText("Pesquizar");
        jButtonpesquiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpesquizaActionPerformed(evt);
            }
        });

        jLabelid.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelid.setText("ID:");

        jTextFieldid.setEnabled(false);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daiana Barbosa\\Documents\\imagens projeto + projeto\\imagens projeto learn java brazil\\CadMedicos.png")); // NOI18N

        javax.swing.GroupLayout jPanelfundoLayout = new javax.swing.GroupLayout(jPanelfundo);
        jPanelfundo.setLayout(jPanelfundoLayout);
        jPanelfundoLayout.setHorizontalGroup(
            jPanelfundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelfundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelfundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelfundoLayout.createSequentialGroup()
                        .addGroup(jPanelfundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelfundoLayout.createSequentialGroup()
                                .addGroup(jPanelfundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelnome, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelcrm, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelid, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelfundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldnome)
                                    .addGroup(jPanelfundoLayout.createSequentialGroup()
                                        .addGroup(jPanelfundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanelfundoLayout.createSequentialGroup()
                                                .addComponent(jTextFieldid)
                                                .addGap(315, 315, 315))
                                            .addGroup(jPanelfundoLayout.createSequentialGroup()
                                                .addComponent(jTextFieldcrm)
                                                .addGap(32, 32, 32)
                                                .addComponent(jLabelespecialização)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBoxespecializações, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(41, 41, 41)))
                                        .addComponent(jLabel1)))
                                .addGap(5, 5, 5))
                            .addGroup(jPanelfundoLayout.createSequentialGroup()
                                .addGap(0, 24, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelfundoLayout.createSequentialGroup()
                        .addComponent(jLabelbusca)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldbusca, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonpesquiza)
                        .addGap(42, 42, 42))))
            .addGroup(jPanelfundoLayout.createSequentialGroup()
                .addGroup(jPanelfundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelfundoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPanelfundoLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jButtonnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtoneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonsalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtoncancelar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelfundoLayout.setVerticalGroup(
            jPanelfundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelfundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelfundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelfundoLayout.createSequentialGroup()
                        .addComponent(jTextFieldnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelfundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelfundoLayout.createSequentialGroup()
                                .addGroup(jPanelfundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldcrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelespecialização)
                                    .addComponent(jComboBoxespecializações, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelfundoLayout.createSequentialGroup()
                        .addComponent(jLabelnome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelcrm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelid)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelfundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtoneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtoncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanelfundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldbusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelbusca)
                    .addComponent(jButtonpesquiza))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(304, 304, 304))
        );

        jLabelcadastro.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabelcadastro.setText("Cadastro de Médicos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabelcadastro))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanelfundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabelcadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelfundo, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(620, 512));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxespecializaçõesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxespecializaçõesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxespecializaçõesActionPerformed

    private void jButtonsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsalvarActionPerformed
if (jTextFieldnome.getText().isEmpty()){
    JOptionPane.showMessageDialog(null, "O campo NOME precisa ser preenchido antes de Salvar");
    jTextFieldnome.requestFocus();
}else if (jTextFieldcrm.getText().isEmpty()){
    JOptionPane.showMessageDialog(null, "O campo CRM precisa ser preenchido antes de salvar");
    jTextFieldcrm.requestFocus();
}else
        
        
        if (flag==1)
{  mod.setNome(jTextFieldnome.getText());
  mod.setCrm (Integer.parseInt(jTextFieldcrm.getText()));
  mod.setEspecialidade((String) jComboBoxespecializações.getSelectedItem());
  dao.salvar(mod);
  jTextFieldnome.setText("");
  jTextFieldcrm.setText("");
  jTextFieldnome.setEnabled(false);
  jTextFieldcrm.setEnabled(false);
  jComboBoxespecializações.setEnabled(false);
  jButtonsalvar.setEnabled(false);
   jTextFieldid.setText("");
   jTextFieldbusca.setText("");
 jButtoncancelar.setEnabled(false);
 jButtoneditar.setEnabled(false);}
else {
    mod.setCodigo (Integer.parseInt(jTextFieldid.getText()));
    mod.setNome(jTextFieldnome.getText());
    mod.setCrm(Integer.parseInt(jTextFieldcrm.getText()));
    mod.setEspecialidade((String) (jComboBoxespecializações.getSelectedItem()))  ;
    dao.editar(mod);
    jTextFieldnome.setEnabled(false);
    jTextFieldcrm.setEnabled(false);
   jComboBoxespecializações.setEnabled(false);
   jButtonsalvar.setEnabled(false);
   jTextFieldnome.setText("");
  jTextFieldcrm.setText("");
  jButtonnovo.setEnabled(true);
  jButtoncancelar.setEnabled(false);
   jTextFieldid.setText("");
    jButtoneditar.setEnabled(false);
   jTextFieldbusca.setText("");
   
}
  
  
  
  
   
    }//GEN-LAST:event_jButtonsalvarActionPerformed

    private void jButtonnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnovoActionPerformed
 preencherTabela("select *from medicos order by nome_medico");
        flag=1;
        jButtonnovo.setEnabled(false);
jTextFieldbusca.setText("");
jTextFieldnome.setText("");
jTextFieldid.setText("");
jTextFieldcrm.setText("");
jButtoneditar.setEnabled(false);
jButtonexcluir.setEnabled(false);
        jButtonsalvar.setEnabled(true);
       jTextFieldnome.setEnabled(true);
       jTextFieldcrm.setEnabled(true);
       jButtoncancelar.setEnabled(true);
       jComboBoxespecializações.setEnabled(true);
       
    }//GEN-LAST:event_jButtonnovoActionPerformed

    private void jTextFieldbuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldbuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldbuscaActionPerformed

    private void jButtonpesquizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpesquizaActionPerformed
jTextFieldnome.setText("");
  jTextFieldcrm.setText("");
     jTextFieldid.setText("");   
        mod.setPesquiza(jTextFieldbusca.getText()); 
       BeansMedico model=dao.buscaMedico(mod);
       jTextFieldid.setText(String.valueOf(model.getCodigo()));
       jTextFieldnome.setText(model.getNome());
       jTextFieldcrm.setText (String.valueOf(model.getCrm()));
       jComboBoxespecializações.setSelectedItem(model.getEspecialidade());
       jButtoneditar.setEnabled(!true);
       jButtonexcluir.setEnabled(!true);
       preencherTabela("select * from medicos where nome_medico like '%"+mod.getPesquiza()+"%'");
      
       
       
       
       
    }//GEN-LAST:event_jButtonpesquizaActionPerformed

    private void jButtoncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncancelarActionPerformed
        jButtonsalvar.setEnabled(false);
       jTextFieldnome.setEnabled(false);
       jTextFieldcrm.setEnabled(false);
       jButtoncancelar.setEnabled(false);
       jComboBoxespecializações.setEnabled(false);
       jButtonnovo.setEnabled(true);
       jButtoneditar.setEnabled(false);
       jButtonexcluir.setEnabled(false);
       jTextFieldnome.setText("");
       jTextFieldbusca.setText("");
       jTextFieldid.setText("");
       jTextFieldcrm.setText("");
        
               
    }//GEN-LAST:event_jButtoncancelarActionPerformed

    private void jButtoneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoneditarActionPerformed
flag=2;
        jButtonsalvar.setEnabled(true);
       jTextFieldnome.setEnabled(true);
       jTextFieldcrm.setEnabled(true);
       jButtoncancelar.setEnabled(true);
       jComboBoxespecializações.setEnabled(true);
       jButtoneditar.setEnabled(false);
       jButtonnovo.setEnabled(false);
       jButtonexcluir.setEnabled(false);
    }//GEN-LAST:event_jButtoneditarActionPerformed

    private void jButtonexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonexcluirActionPerformed
        int resposta= JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir o cadastro?");
        if(resposta==JOptionPane.YES_OPTION){
        mod.setCodigo(Integer.parseInt(jTextFieldid.getText()));
        dao.excluir(mod);
        jTextFieldid.setText("");
        jTextFieldnome.setText("");
        jTextFieldcrm.setText("");
        jTextFieldid.setEnabled(false);
        jTextFieldnome.setEnabled(false);
        jTextFieldcrm.setEnabled(false);
        jButtonnovo.setEnabled(true);
        jButtoncancelar.setEnabled(false);
        jButtoneditar.setEnabled(false);
        jButtonexcluir.setEnabled(false);
        
        
        } 
        
    }//GEN-LAST:event_jButtonexcluirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // evento adicionado para aparecer o medico salvo automaticamente no tabela 
        preencherTabela("select *from medicos order by nome_medico");
    }//GEN-LAST:event_formWindowActivated

    private void jTablebuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablebuscaMouseClicked
        String nome_medico=""+jTablebusca.getValueAt(jTablebusca.getSelectedRow(), 1);
        conex.conexao();
        conex.executasql("select *from medicos where nome_medico='"+nome_medico+"'");
    try {
        conex.rs.first();
        jTextFieldid.setText(String.valueOf(conex.rs.getInt("cod_medico")));
        jTextFieldnome.setText(conex.rs.getString("nome_medico"));
        jTextFieldcrm.setText(String.valueOf(conex.rs.getInt("crm_medico")));
        jComboBoxespecializações.setSelectedItem(conex.rs.getString("especialidade_medico"));
    } catch (SQLException ex) {
        Logger.getLogger(FormMedico.class.getName()).log(Level.SEVERE, null, ex);
    }
    jButtoneditar.setEnabled(true);
    jButtonexcluir.setEnabled(true);
    jButtoncancelar.setEnabled(true);
        conex.desconect();
    }//GEN-LAST:event_jTablebuscaMouseClicked

    /**
     * @param args the command line arguments
     */
    public void preencherTabela(String sql){
     ArrayList dados = new ArrayList();
     String [] colunas=new String []{"ID","Nome","Especialidade","Crm"};
     conex.conexao();
     conex.executasql(sql);
    try {
        conex.rs.first();
        do{
          dados.add(new Object[]{conex.rs.getInt("cod_medico"),conex.rs.getString("nome_medico"),conex.rs.getString("especialidade_medico"),conex.rs.getInt("crm_medico")});
        }while(conex.rs.next());
       
    } catch (SQLException ex) {
        //JOptionPane.showMessageDialog(null,"busca n encontrada");
    }
    ModeloTabela modelo = new ModeloTabela(dados,colunas);
    jTablebusca.setModel(modelo);
    jTablebusca.getColumnModel().getColumn(0).setPreferredWidth(33);
    jTablebusca.getColumnModel().getColumn(0).setResizable(false);
    jTablebusca.getColumnModel().getColumn(1).setPreferredWidth(225);
    jTablebusca.getColumnModel().getColumn(1).setResizable(false);
    jTablebusca.getColumnModel().getColumn(2).setPreferredWidth(200);
    jTablebusca.getColumnModel().getColumn(2).setResizable(false);
    jTablebusca.getColumnModel().getColumn(3).setPreferredWidth(70);
    jTablebusca.getColumnModel().getColumn(3).setResizable(false);
    jTablebusca.getTableHeader().setReorderingAllowed(false);
    jTablebusca.setAutoResizeMode(jTablebusca.AUTO_RESIZE_OFF);
    jTablebusca.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    
    
    
     conex.desconect();
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtoncancelar;
    private javax.swing.JButton jButtoneditar;
    private javax.swing.JButton jButtonexcluir;
    private javax.swing.JButton jButtonnovo;
    private javax.swing.JButton jButtonpesquiza;
    private javax.swing.JButton jButtonsalvar;
    private javax.swing.JComboBox jComboBoxespecializações;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelbusca;
    private javax.swing.JLabel jLabelcadastro;
    private javax.swing.JLabel jLabelcrm;
    private javax.swing.JLabel jLabelespecialização;
    private javax.swing.JLabel jLabelid;
    private javax.swing.JLabel jLabelnome;
    private javax.swing.JPanel jPanelfundo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTablebusca;
    private javax.swing.JTextField jTextFieldbusca;
    private javax.swing.JTextField jTextFieldcrm;
    private javax.swing.JTextField jTextFieldid;
    private javax.swing.JTextField jTextFieldnome;
    // End of variables declaration//GEN-END:variables
}
