/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import ModeloConection.ConexaoBD;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Daiana Barbosa
 */
public class TelaPrincipal extends javax.swing.JFrame {

   ConexaoBD conecta=new ConexaoBD();
   FormMedico telamedico =new FormMedico();
    FormUsuario telausuario =new FormUsuario();
    FormPacientes telapaciente=new FormPacientes();
   
    public TelaPrincipal(String usu) {
        initComponents();
        jLabelusuario.setText(usu);
        conecta.conexao();
    }
    public TelaPrincipal(){
         initComponents();
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox();
        jInternalFrameinterno = new javax.swing.JInternalFrame();
        jButtonfechar = new javax.swing.JButton();
        jPanelinterno = new javax.swing.JPanel();
        jButtonusuarios = new javax.swing.JButton();
        jLabelusuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelcadastro = new javax.swing.JLabel();
        jLabelagenda = new javax.swing.JLabel();
        medico = new javax.swing.JButton();
        jButtonenfermeira = new javax.swing.JButton();
        jButtonpacientes = new javax.swing.JButton();
        jButtonagenda = new javax.swing.JButton();
        jLabelpainelfundo = new javax.swing.JLabel();
        jLabelgerencia = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenucadastro = new javax.swing.JMenu();
        jMenuItemCadmedicos = new javax.swing.JMenuItem();
        jMenuItemCadenfermeiros = new javax.swing.JMenuItem();
        jMenuItemCadpacientes = new javax.swing.JMenuItem();
        jMenuItemCadusuarios = new javax.swing.JMenuItem();
        jMenurelatorio = new javax.swing.JMenu();
        jMenuferramentas = new javax.swing.JMenu();
        jMenuItemTelaBemVindo = new javax.swing.JMenuItem();
        jMenusair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        jRadioButton1.setText("jRadioButton1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrameinterno.setTitle("Bem-Vindo");
        jInternalFrameinterno.setVisible(true);
        jInternalFrameinterno.getContentPane().setLayout(null);

        jButtonfechar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daiana Barbosa\\Documents\\imagens projeto + projeto\\imagens projeto learn java brazil\\exit.png")); // NOI18N
        jButtonfechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonfecharActionPerformed(evt);
            }
        });
        jInternalFrameinterno.getContentPane().add(jButtonfechar);
        jButtonfechar.setBounds(630, 0, 30, 30);

        jPanelinterno.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelinterno.setLayout(null);

        jButtonusuarios.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daiana Barbosa\\Documents\\imagens projeto + projeto\\clientes.png")); // NOI18N
        jButtonusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonusuariosActionPerformed(evt);
            }
        });
        jPanelinterno.add(jButtonusuarios);
        jButtonusuarios.setBounds(230, 90, 60, 60);

        jLabelusuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanelinterno.add(jLabelusuario);
        jLabelusuario.setBounds(130, 280, 180, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Usuario Logado:");
        jPanelinterno.add(jLabel1);
        jLabel1.setBounds(20, 280, 110, 17);

        jLabelcadastro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelcadastro.setText("Cadastros -");
        jPanelinterno.add(jLabelcadastro);
        jLabelcadastro.setBounds(40, 20, 80, 17);

        jLabelagenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelagenda.setText("Agenda -");
        jPanelinterno.add(jLabelagenda);
        jLabelagenda.setBounds(40, 180, 70, 20);

        medico.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daiana Barbosa\\Documents\\imagens projeto + projeto\\imagens projeto learn java brazil\\CadMedicos.png")); // NOI18N
        medico.setToolTipText("cadastro de medicos");
        medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicoActionPerformed(evt);
            }
        });
        jPanelinterno.add(medico);
        medico.setBounds(160, 90, 60, 60);

        jButtonenfermeira.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daiana Barbosa\\Documents\\imagens projeto + projeto\\imagens projeto learn java brazil\\icon-infermeira.png")); // NOI18N
        jButtonenfermeira.setToolTipText("Cadastro de enfermeiras");
        jButtonenfermeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonenfermeiraActionPerformed(evt);
            }
        });
        jPanelinterno.add(jButtonenfermeira);
        jButtonenfermeira.setBounds(90, 90, 60, 60);

        jButtonpacientes.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daiana Barbosa\\Documents\\imagens projeto + projeto\\imagens projeto learn java brazil\\cadPacientes.png")); // NOI18N
        jButtonpacientes.setToolTipText("Cadastrar pacientes");
        jButtonpacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpacientesActionPerformed(evt);
            }
        });
        jPanelinterno.add(jButtonpacientes);
        jButtonpacientes.setBounds(20, 90, 60, 60);

        jButtonagenda.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daiana Barbosa\\Documents\\imagens projeto + projeto\\imagens projeto learn java brazil\\Agenda.png")); // NOI18N
        jButtonagenda.setToolTipText("Agendamento");
        jButtonagenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonagendaActionPerformed(evt);
            }
        });
        jPanelinterno.add(jButtonagenda);
        jButtonagenda.setBounds(30, 210, 70, 60);

        jLabelpainelfundo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelpainelfundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daiana Barbosa\\Documents\\imagens projeto + projeto\\internalframe.png")); // NOI18N
        jPanelinterno.add(jLabelpainelfundo);
        jLabelpainelfundo.setBounds(10, 10, 640, 290);

        jInternalFrameinterno.getContentPane().add(jPanelinterno);
        jPanelinterno.setBounds(10, 20, 650, 310);

        jLabelgerencia.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        jLabelgerencia.setText("Gereciamento do Sistema");
        jInternalFrameinterno.getContentPane().add(jLabelgerencia);
        jLabelgerencia.setBounds(80, 0, 170, 20);

        getContentPane().add(jInternalFrameinterno);
        jInternalFrameinterno.setBounds(10, 10, 690, 370);

        jMenucadastro.setText("Cadastros");

        jMenuItemCadmedicos.setText("Médicos");
        jMenuItemCadmedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadmedicosActionPerformed(evt);
            }
        });
        jMenucadastro.add(jMenuItemCadmedicos);

        jMenuItemCadenfermeiros.setText("Enfêrmeiros");
        jMenuItemCadenfermeiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadenfermeirosActionPerformed(evt);
            }
        });
        jMenucadastro.add(jMenuItemCadenfermeiros);

        jMenuItemCadpacientes.setText("Paciêntes");
        jMenuItemCadpacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadpacientesActionPerformed(evt);
            }
        });
        jMenucadastro.add(jMenuItemCadpacientes);

        jMenuItemCadusuarios.setText("Usuários");
        jMenuItemCadusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadusuariosActionPerformed(evt);
            }
        });
        jMenucadastro.add(jMenuItemCadusuarios);

        jMenuBar1.add(jMenucadastro);

        jMenurelatorio.setText("Relatórios");
        jMenuBar1.add(jMenurelatorio);

        jMenuferramentas.setText("Ferramentas");

        jMenuItemTelaBemVindo.setText("Tela Bem-Vindo");
        jMenuItemTelaBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTelaBemVindoActionPerformed(evt);
            }
        });
        jMenuferramentas.add(jMenuItemTelaBemVindo);

        jMenuBar1.add(jMenuferramentas);

        jMenusair.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenusair.add(jMenuItemSair);

        jMenuBar1.add(jMenusair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(729, 453));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadmedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadmedicosActionPerformed
    
       try {
           conecta.executasql("select * from usuarios where nome_usu = '"+
                   jLabelusuario.getText().trim() +"'");
           conecta.rs.first();
           if((conecta.rs.getString("tipo_usu")).trim().equals("administrador")){

               telamedico.setVisible(true);
           } 
           else
           {JOptionPane.showMessageDialog(null, "você nao tem permissão de ADM !!");}
       } catch (SQLException ex) {
           Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
       }
    
    }//GEN-LAST:event_jMenuItemCadmedicosActionPerformed

    private void jMenuItemCadenfermeirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadenfermeirosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCadenfermeirosActionPerformed

    private void jButtonenfermeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonenfermeiraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonenfermeiraActionPerformed

    private void jButtonagendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonagendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonagendaActionPerformed

    private void jButtonfecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonfecharActionPerformed
       jInternalFrameinterno.dispose();
    }//GEN-LAST:event_jButtonfecharActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
           // conecta.desconect();
             System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemTelaBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTelaBemVindoActionPerformed
      jInternalFrameinterno.show();
    }//GEN-LAST:event_jMenuItemTelaBemVindoActionPerformed

    private void medicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicoActionPerformed
       
       try {
           conecta.executasql("select * from usuarios where nome_usu='"+jLabelusuario.getText()+"'");
           conecta.rs.first();
           if (conecta.rs.getString("tipo_usu").equals("administrador")){
         telamedico.setVisible(true);
           } else {JOptionPane.showMessageDialog(null,"Você nao tem permissoes para acessar !");}
       } catch (SQLException ex) {
           Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
       }
       
    }//GEN-LAST:event_medicoActionPerformed

    private void jMenuItemCadusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadusuariosActionPerformed
      try {
           conecta.executasql("select * from usuarios where nome_usu='"+jLabelusuario.getText()+"'");
           conecta.rs.first();
           if (conecta.rs.getString("tipo_usu").equals("administrador")){
      telausuario.setVisible(true); 
           } else {JOptionPane.showMessageDialog(null,"Você nao tem permissoes para acessar !");}
       } catch (SQLException ex) {
           Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_jMenuItemCadusuariosActionPerformed

    private void jButtonusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonusuariosActionPerformed
       try {
           conecta.executasql("select * from usuarios where nome_usu='"+jLabelusuario.getText()+"'");
           conecta.rs.first();
           if (conecta.rs.getString("tipo_usu").equals("administrador")){
       
      telausuario.setVisible(true); 
           } else {JOptionPane.showMessageDialog(null,"Você nao tem permissoes para acessar !");}
       } catch (SQLException ex) {
           Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_jButtonusuariosActionPerformed

    private void jMenuItemCadpacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadpacientesActionPerformed
        
       try {
           conecta.executasql("select * from usuarios where nome_usu = '"+
                   jLabelusuario.getText().trim() +"'");
           conecta.rs.first();
           if((conecta.rs.getString("tipo_usu")).trim().equals("administrador")){

               telapaciente.setVisible(true);
           } 
           else
           {JOptionPane.showMessageDialog(null, "você nao tem permissão de ADM !!");}
       } catch (SQLException ex) {
           Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
       }
    
    
    }//GEN-LAST:event_jMenuItemCadpacientesActionPerformed

    private void jButtonpacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpacientesActionPerformed
        try {
           conecta.executasql("select * from usuarios where nome_usu = '"+
                   jLabelusuario.getText().trim() +"'");
           conecta.rs.first();
           if((conecta.rs.getString("tipo_usu")).trim().equals("administrador")){

               telapaciente.setVisible(true);
           } 
           else
           {JOptionPane.showMessageDialog(null, "você nao tem permissão de ADM !!");}
       } catch (SQLException ex) {
           Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_jButtonpacientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonagenda;
    private javax.swing.JButton jButtonenfermeira;
    private javax.swing.JButton jButtonfechar;
    private javax.swing.JButton jButtonpacientes;
    private javax.swing.JButton jButtonusuarios;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JInternalFrame jInternalFrameinterno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelagenda;
    private javax.swing.JLabel jLabelcadastro;
    private javax.swing.JLabel jLabelgerencia;
    private javax.swing.JLabel jLabelpainelfundo;
    private javax.swing.JLabel jLabelusuario;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCadenfermeiros;
    private javax.swing.JMenuItem jMenuItemCadmedicos;
    private javax.swing.JMenuItem jMenuItemCadpacientes;
    private javax.swing.JMenuItem jMenuItemCadusuarios;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemTelaBemVindo;
    private javax.swing.JMenu jMenucadastro;
    private javax.swing.JMenu jMenuferramentas;
    private javax.swing.JMenu jMenurelatorio;
    private javax.swing.JMenu jMenusair;
    private javax.swing.JPanel jPanelinterno;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JButton medico;
    // End of variables declaration//GEN-END:variables
}
