/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import ModeloConection.ConexaoBD;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Daiana Barbosa
 */
public class TelaLogin extends javax.swing.JFrame {

   ConexaoBD con=new ConexaoBD();
   
    public TelaLogin() {
        initComponents();
        con.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonacessar = new javax.swing.JButton();
        jButtonsair = new javax.swing.JButton();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabelLogo = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jLabelFundoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonacessar.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jButtonacessar.setText("Acessar");
        jButtonacessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonacessarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonacessar);
        jButtonacessar.setBounds(230, 180, 100, 40);

        jButtonsair.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jButtonsair.setText("Sair");
        jButtonsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonsair);
        jButtonsair.setBounds(350, 180, 100, 40);

        jLabelUsuario.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabelUsuario.setText("Usuário:");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(160, 100, 70, 19);

        jLabelSenha.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabelSenha.setText("Senha:");
        getContentPane().add(jLabelSenha);
        jLabelSenha.setBounds(160, 130, 50, 19);

        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsuario);
        jTextFieldUsuario.setBounds(230, 90, 220, 30);

        jLabelLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daiana Barbosa\\Desktop\\java-logo-transparent-2.png")); // NOI18N
        getContentPane().add(jLabelLogo);
        jLabelLogo.setBounds(-60, 30, 300, 270);
        getContentPane().add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(230, 130, 220, 30);

        jLabelFundoLogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daiana Barbosa\\Documents\\imagens projeto + projeto\\imagens projeto learn java brazil\\fundotelaLogin.png")); // NOI18N
        getContentPane().add(jLabelFundoLogin);
        jLabelFundoLogin.setBounds(0, 1, 500, 250);

        setSize(new java.awt.Dimension(515, 288));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonacessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonacessarActionPerformed
       
       /** if (jTextFieldUsuario.getText().equals("admin")&&(jPasswordFieldSenha.getText().equals("1234")))
        {
        TelaPrincipal tela=new TelaPrincipal();
        tela.setVisible(true);
        dispose();  
        }
        else 
            JOptionPane.showMessageDialog(rootPane, "login errado");
        */
        
       try {
           con.executasql("select *from usuarios where nome_usu = '"+ jTextFieldUsuario.getText() +"'");
           con.rs.first();
           if((con.rs.getString("senha_usu").trim()).equals(jPasswordFieldSenha.getText().trim())){
               TelaPrincipal tela=new TelaPrincipal(jTextFieldUsuario.getText().trim());
               tela.setVisible(true);
               dispose();
           }
           else {
               JOptionPane.showMessageDialog(null, " senha incorretos");
           }
       } catch (SQLException ex) {
         JOptionPane.showMessageDialog(null, "Usuario incorreto");
       }
        
    }//GEN-LAST:event_jButtonacessarActionPerformed

    private void jButtonsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsairActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jButtonsairActionPerformed

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonacessar;
    private javax.swing.JButton jButtonsair;
    private javax.swing.JLabel jLabelFundoLogin;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
